#!/bin/bash -l

#SBATCH --nodes=4
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=20
#SBATCH --mem=96G
#SBATCH --partition=gpu
#SBATCH --qos=gpu
#SBATCH --gres=gpu:2
#SBATCH --time=72:00:00
#SBATCH --output=/scratch/izar/jiguo/train/cocodet/resnet50_fpn1024/%x.out

shopt -s extglob

export MASTER_ADDR=$(hostname)
export MASTER_PORT=7247
export TORCH_DISTRIBUTED_DEBUG=INFO


echo STARTING AT `date`


xpdir="/scratch/izar/jiguo/train/cocodet/resnet50_fpn1024/${SLURM_JOB_NAME}"
checkpoint="/scratch/izar/jiguo/train/cocodet/resnet50_fpn1024/opp_train_resnet50_fpn1024_cocodet/checkpoints/opp_train_resnet50_fpn1024_cocodet.pt.epoch28"
optimizer_cp="/scratch/izar/jiguo/train/cocodet/resnet50_fpn1024/opp_train_resnet50_fpn1024_cocodet/checkpoints/opp_train_resnet50_fpn1024_cocodet.pt.optim.epoch28"
mkdir -p ${xpdir}
mkdir -p ${xpdir}/code
tar -czvf ${xpdir}/code/code.tar.gz /home/jiguo/openpifpaf
mkdir -p ${xpdir}/logs


cd ..

mkdir -p ${xpdir}/checkpoints

srun --gpu-bind=closest /bin/bash -c "time python3 -m openpifpaf.train --ddp \
  --output ${xpdir}/checkpoints/${SLURM_JOB_NAME}.pt \
  --dataset=cocodet \
  --cocodet-square-edge=513 \
  --cocodet-extended-scale \
  --cocodet-orientation-invariant=0.1 \
  --cocodet-upsample=2 \
  --checkpoint=${checkpoint} \
  --resume-training=${optimizer_cp} \
  --necknet=FPN \
  --neck_in 512 1024 2048 \
  --neck_out=1024 \
  --num_outs=3 \
  --start_level=0 \
  --base_outstage 2 3 4 \
  --head_stride 4 8 16 \
  --epochs=150 \
  --batch-size=8 \
  --lr=0.0001 \
  --lr-decay 130 140 \
  --lr-decay-epochs=10 \
  --momentum=0.9 \
  --weight-decay=1e-5 \
  --b-scale=10.0 \
  --clip-grad-value=10.0 \
  2>&1 | tee ${xpdir}/logs/${SLURM_JOB_NAME}.log"

cd -


echo FINISHED at `date`
